### ISSUE TITLE
The bot can't select the menu

### ISSUE THREAD

**Issue by arkiny22** [Sovamorco/BHBot#1]
The bot scrolls me every time, and can't "choose to create a custom game room."
If you create a room yourself, it will also scroll through the character selection.

**Comment by Sovamorco** [comment]
Can you please send a log of the session where the bug occurs
Logs should be in %localappdata%\BHBot\logs
Also, just in case, make sure the ingame language is set to English and your screen is 1920x1080

**Comment by arkiny22** [comment]
The problem was in the language, I changed it and the bot started working)
[20210421-005805.log](https://github.com/Sovamorco/BHBot/files/6346914/20210421-005805.log)
[20210421-004052.log](https://github.com/Sovamorco/BHBot/files/6346916/20210421-004052.log)

**Comment by Sovamorco** [comment]
Thanks for your feedback, I'll update the limitations section in readme to include info about the language :)
