### ISSUE TITLE
BHBot keeps selecting and closing the option exit Brawlhalla

### ISSUE THREAD

**Issue by NOTdeKaaskop** [Sovamorco/BHBot#10]
After opening BHBot and starting the bot Brawlhalla starts. But after that it keeps selecting the option to exit Brawlhalla. Is there a way to fix this?

Settings I use:
Mode: leveling up one character
Character: Asuri
Duration: 15
Automatic xp limit reset: on
Automatic xp limit detection: on
Reset frequency: 5.0
Reset wait duration: 30
Bots amount: 7
Disable sound: on

**Comment by NOTdeKaaskop** [comment]
I enabled the print debug option and it says DEBUG not in menu, is this the problem?

**Comment by Sovamorco** [comment]
Is your in-game language set to English? Did you move or resize the window after the game started?
If both of these are ok then send me a screenshot of the Brawlhalla main menu, please.

**Comment by NOTdeKaaskop** [comment]
Sorry for the late response. It looks like this.


https://user-images.githubusercontent.com/90102775/132119394-46286179-8342-4dbf-9d82-d86f84fa9901.mp4

**Comment by Sovamorco** [comment]
I'm really sorry for this one, I somehow messed up pixel detection in menu even though it's stable. I'll release an update to stable like.. about now.
