### ISSUE TITLE
Bot malfunctioning, not opening correctly

### ISSUE THREAD

**Issue by jo5000** [Sovamorco/BHBot#11]
Hi, I checked the settings so that the client would not be hidden so I could view what is happening, however Brawlhalla would always open shifted to the bottom right corner of my screen and this would throw off character selection. For example, selecting Artemis in the settings would put on Sidra. 
When I decided to check off stealth mode, the bot isn't able to do anything but I'm unsure why since everything is hidden. The program does say that it's starting game and fighting but when I ended it after an hour run, there was no exp gained or anything of that sort.

**Comment by jo5000** [comment]
I'm so sorry I did not check the previous closed issues since I am new to this website. Problem was solved after viewing them, extremely sorry about this.

**Comment by Sovamorco** [comment]
It's alright, you are always welcome to open issues no matter what happens. So feel free and don't be sorry. I'm glad you figured it out on your own tho :)
