### ISSUE TITLE
The bot just scrolls in the main menu

### ISSUE THREAD

**Issue by Brunardobich** [Sovamorco/BHBot#14]
The bot doesn't start any game, it just scrolls on the main menu, the game is windowed and in english even in stealth mode it doesn´t start farming

**Comment by Sovamorco** [comment]
That's weird. Can you please send me:
1. What OS you are on
2. If you are on tech beta or not
3. Screenshot of the menu (just making a screenshot in fullscreen is good, I specifically need the menu entries on the left and small buttons on the top right so if you want you can remove all identifying info)
4. Logs that are located at %LOCALAPPDATA%/BHBot/logs (just take the latest session that the bug occured in)

**Comment by Sovamorco** [comment]
I just pushed a new beta update. Please:
- Change the update branch to "beta" in settings
- Restart the bot
- Install update
- Try new "Legacy menu detection" option
