### ISSUE TITLE
Invalid State

### ISSUE THREAD

**Issue by TalEdd** [Sovamorco/BHBot#16]
It keeps saying bot is in invalid state. Something went wrong. It might the new white ui changes due to the anniversary even, but I don't know for sure.

**Comment by Sovamorco** [comment]
It's not due to ui change, as bot should hopefully work with any menu updates now
Can you tell me your OS version and send logs? (they are located in %LOCALAPPDATA%\BHBot\logs)
Just send the latest one in which the error occurred (not exceptions but the one with date in the name)

**Comment by TalEdd** [comment]
It's seems I'm dumb. In stealth mode it's working again, for whatever reason. I had somehow turned off that setting😑.

**Comment by Sovamorco** [comment]
Glad to know it's working for you now. Feel free to open new issues if any further problems arise
