### ISSUE TITLE
Bot gets stuck in meet the legends menu

### ISSUE THREAD

**Issue by NoxoDot** [Sovamorco/BHBot#19]
So basically the bot goes into the "meet the legends" menu and it just cylces through the sort option.
Any way to fix this?

**Comment by Sovamorco** [comment]
Can you please send a screenshot of "Meet the legends" window?

**Comment by NoxoDot** [comment]
![Capture](https://user-images.githubusercontent.com/94503675/144105623-2a6e9ef4-b647-46b0-ac28-24bf0a0bce84.PNG)

**Comment by Sovamorco** [comment]
Thanks. I'll try to figure it out when I have time

**Comment by NoxoDot** [comment]
ok thank you

**Comment by Sovamorco** [comment]
For some reason it seems that the colors are a bit off. Do you have anything installed that may explain that? Afaik Brawlhalla itself does not have any options for colors.
But it also can be because of something else, I'm not sure.

Can you also send:
- Your OS version
- A fullscreen screenshot of the same window with characters sorted by date

Thanks

**Comment by NoxoDot** [comment]
My os is: Windows 10.0.19043 Build 19043
![Capture](https://user-images.githubusercontent.com/94503675/144111893-c3975aa0-203a-473f-9c6b-46171bae9b2e.PNG)

**Comment by Sovamorco** [comment]
Oh, sorry for asking again, but can you make it fullscreen (in game settings and send send a fullscreen screenshot). Thanks. I just want to check the color value for the pixel that the bot is checking, patch it in and then see if it works. Maybe that's a problem purely with mtl, because it's a bit tricky

**Comment by NoxoDot** [comment]
sure, here it is
![Brawlhalla_2021 11 30-20 27](https://user-images.githubusercontent.com/94503675/144114541-1a5baed3-2da3-4248-97ec-f985d1912544.png)

**Comment by Sovamorco** [comment]
Try to
1. Change update branch to beta in BHBot settings
2. Restart the bot
3. Update to latest beta version
4. Start it again

For some reason the color value is different and I am not sure if this may ruin detection in some other places as well

**Comment by NoxoDot** [comment]
i tried and now im getting this error 
"Error recognizing level
Bot only works with levels 1-100
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 954, in _bootstrap_inner
  File "threading.py", line 892, in run
  File "bot.py", line 350, in main_loop
  File "bot.py", line 315, in main_sequence
  File "bot.py", line 111, in initialize
  File "bot.py", line 447, in get_characters
  File "levels.py", line 86, in get_level
levels.LevelNotDetected"

**Comment by Sovamorco** [comment]
Yep, because of the colors it seems. I don't really know how to help if I can't determine what's changing them, sorry  :(

**Comment by NoxoDot** [comment]
could it be like some monitor options?

**Comment by Sovamorco** [comment]
Definitely no, because they don't affect screenshots. It cahn, however, be something in windows settings, anything color-related not set on the actual monitor may be the reason ig.

**Comment by NoxoDot** [comment]
i got it to work
i just changed the refresh-rate from 165hz to 144hz and now it works

**Comment by Sovamorco** [comment]
That's.... extremely weird, but I'm glad it worked. And thanks for all the info, I'll try to look into it and maybe also make an algorithm that does not rely on pixel detection (it will probably be more bannable though).
