### ISSUE TITLE
brawlhalla crushes instantly after starting . keeps crushing

### ISSUE THREAD

**Issue by Nikorpl** [Sovamorco/BHBot#23]
i have newest version of bot and all settings set well . bot says Found Brawlhalla and i see loading screen for a second , then game disapeard , restarting and again same thing . pls help

**Comment by MidnightD4wn** [comment]
make sure windows scaling is 100% not 125% or anything else

**Comment by Nikorpl** [comment]
scaling is 100% and i checked so many things that may disturb bot and i found nothing

**Comment by Sovamorco** [comment]
If you have stealth mode on then that's exactly what's supposed to happen, bot automatically hides the game window because, well.... that's what stealth mode is for
