### ISSUE TITLE
The bot cannot select a character

### ISSUE THREAD

**Issue by arkiny22** [Sovamorco/BHBot#3]
Запуская бота, он создает лоби, по логам видно что он выбрал персонажа, но персонаж не выбирается и идет ожидание
Если я сам выберу персонажа бот начинает нормально работать, идет какой сбой
-------------------------------------------------------------------------------------------------

Launching the bot, it creates lobi, according to the logs it can be seen that it has selected a character, but the character is not selected and there is a wait
If I choose a character myself, the bot starts working normally, what kind of failure is going on
[20210427-071135.log](https://github.com/Sovamorco/BHBot/files/6391167/20210427-071135.log)

**Comment by Sovamorco** [comment]
Сразу чтобы проверить, проблема может быть в том что

1. Подключен геймпад и игра определяет основного игрока как использующего геймпад. Маловероятно, и такого происходить не должно, но на всякий случай стоит проверить.
2. Раскладка клавиатуры в игре стоит не по умолчанию. Тогда надо поменять клавиши в настройках горячих клавиш. За выбор персонажа отвечает клавиша быстрой атаки (по умолчанию J).

Если по этим двум пунктам все хорошо, то буду думать что еще могло пойти не так.

**Comment by arkiny22** [comment]
Геймпад не подключен. Решил проверит проблему с раскладкой, все также, выбирает персонажа, но, нашлась еще одна ошибка, запустил бота без стелс режима, теперь он просто выбирает меню выхода( и так идет по кругу) 
Ктсати, заметил только что, что это происходи в полноэкранном режиме, в окном такого нет(про то что бот выбирает меню выхода) В полноэкранном режиме же, бот как-будто встает в ступор, и не может ничего выбрать

[20210428-132029.log](https://github.com/Sovamorco/BHBot/files/6391349/20210428-132029.log)

**Comment by Sovamorco** [comment]
Игра **должна быть** в оконном режиме и переводить ее в полноэкранный или трогать что-либо после запуска игры не стоит, ибо это может поломать размер окна. 
Спасибо за логи. Я понял что да, был не прав, и если проблема была бы в раскладке бот не смог бы и пункты меню выбирать. Попробую посмотреть в чем проблема и почему именно персонаж не выбирается.
И еще, можно попросить скрин лобби после того как бот зависает, если не сложно?
Для этого можно запустить бота без стелс-режима, дождаться пока он застрянет и после этого остановить, перевести игру в полноэкранный и сделать скрин.
Заранее спасибо :)

**Comment by arkiny22** [comment]
Могу записать видео, если нужно)

**Comment by Sovamorco** [comment]
Еще лучше. Тогда можете отправить видео сюда, либо на sovamorco@sovamor.co (ибо я честно не знаю ограничения гитхаба на файлы).

**Comment by arkiny22** [comment]
![image](https://user-images.githubusercontent.com/56174641/116395810-4801bc00-a82d-11eb-8a02-1af2f910b37d.png)
Кстати, забыл еще уточнить, то что, когда навожусь на персонажа, бот выбирает автоматически его и запускает игру

**Comment by Sovamorco** [comment]
Окей, я понял в чем проблема. Бот почему-то думает что у вас разблокированы все персонажи. Можете кинуть скрины, например, Бринн и Тора из вкладки с информацией о персонажах?

**Comment by arkiny22** [comment]
![image](https://user-images.githubusercontent.com/56174641/116396724-63b99200-a82e-11eb-82ba-52c25a9c69c4.png)
![image](https://user-images.githubusercontent.com/56174641/116396806-7633cb80-a82e-11eb-9a63-dd3c700f0a95.png)
Тоже замечал в логах что все персонажи разблокированы

**Comment by arkiny22** [comment]
Вот видео: https://youtu.be/if5-psNLdrk

**Comment by Sovamorco** [comment]
Выпустил обновление, проверьте, пожалуйста.

**Comment by arkiny22** [comment]
Все отлично работает) 
Очень благодарен что помогли мне)))

**Comment by Sovamorco** [comment]
Вам спасибо за репорт. Приятного использования :)
