### ISSUE TITLE
All characters loaded as "Unlocked" even the ones I don't have

### ISSUE THREAD

**Issue by 0x00G** [Sovamorco/BHBot#30]
All characters even the ones I don't have are set as "unlocked" so it gets stuck on selecting a character because it chooses a character I don't really own.

**Comment by Sovamorco** [comment]
Thanks for reporting. Missed that and probably know why that is, I'll fix it later today

**Comment by 0x00G** [comment]
Any update on this issue? Thanks.

**Comment by Sovamorco** [comment]
Sorry, didn't have the time, I'll fix it when I have some

**Comment by Sovamorco** [comment]
Should be fixed in 3.5.17. You can download it either from bot's autoupdate, or if that does not work - from https://sovamor.co/bhbot
