### ISSUE TITLE
Bot just cycles home screen

### ISSUE THREAD

**Issue by KritikPant** [Sovamorco/BHBot#4]
After the TMNT update, the bot just cycles through the home screen options. I have tried manually pressing enter to go into the character screen so that it goes through the characters but then it just cycles through the characters instead of collecting info.

**Comment by Sovamorco** [comment]
Thanks for bringing that up, I wasn't really playing bh lately, so I didn't know latest update broke the bot. It should be fixed in the latest update (3.3.11).
