### ISSUE TITLE
Doesn't choose custom game

### ISSUE THREAD

**Issue by krazziu** [Sovamorco/BHBot#6]
When loaded into the main menu the bot goes to meet the legends instead of custom game. I'm not sure why but please fix this.

**Comment by Sovamorco** [comment]
Does it not go to Custom Game afterwards?
It goes to Meet the Legends at first to collect character information for modes, stats and automatic xp limit reset to function because bot has to know current character level amd progress, and if they're unlocked as well.

**Comment by krazziu** [comment]
Oh I wasn't sure if that was a bug or not. Maybe I was just impatient instead of waiting. How long does it usually take?

**Comment by Sovamorco** [comment]
It depends on the system, bot has to cycle through all of the characters. For me it takes at most a minute. Main reason behind that (besides all i've listed) is that you need to know which specific characters are unlocked to know where the desired character is to pick them. You can technically disable this info collection by making a custom mode, but it'll disable all the features i've listed previously and will only work with all of the characters unlocked and is generally not recommended and will probably be deprecated at some point.

**Comment by krazziu** [comment]
Got it. Appreciate the fast responses. Have a great day.

**Comment by Sovamorco** [comment]
Thanks, and feel free to open more issues if you have any problems, questions or suggestions going forward, it's always appreciated

**Comment by krazziu** [comment]
So I have another issue. The bot is cycling through the "Sort:" portion of the Meet the Legends tab. It's been cycling through it for almost 30 minutes.

**Comment by Sovamorco** [comment]
Oh.. that's odd, yes. First of all, make sure to not touch the game window in any way after it opens (moving or resizing in will break the bot), and that your language is set to English. If both of these are ok, please send me a screenshot of your Meet the Legends window.

**Comment by krazziu** [comment]
Turned on debug. It seems like the bot is having issues trying to set the legends by Date. Here's a picture - https://imgur.com/a/vdczuDr

**Comment by Sovamorco** [comment]
Are you on Windows 11 per chance? I am not sure what changes it may cause and I don't think it's fully possible for me to test right now. And I probably won't be supporting it until it fully comes out. For now, if your screen is 1920x1080, you can
1. Put Brawlhalla into fullscreen
2. Make a screenshot of Meet the Legends again
3. Send it to me as an attachment to comment here (insted of through imgur as it may compress images which can mess up data for pixel detection)
And I will try to work out if it's a problem with Brawlhalla and changed pixels or with Windows 11 and difference in win32 api behavior.

**Comment by krazziu** [comment]
Oh yeah it might be a Windows 11 issue. I upgraded around a week ago. There are a ton of bugs so I might switch back to Windows 10. If it isn't I will definitely send you a picture.

**Comment by Sovamorco** [comment]
Thanks. Windows 11 support is planned but after it's released as working around bugs that may be fixed anyway is a waste of time from my perspective.
And again, thanks for opening an issue, didn't really think about that before.

**Comment by krazziu** [comment]
I can confirm that this is a Windows 11 issue. Just downgraded back down to Windows 10 and it's working perfectly fine.

**Comment by Sovamorco** [comment]
Thanks. I'll look into that more at some point but for now I'll just add a point to readme regarding that.
