### ISSUE TITLE
Bot won't reach "Meet the legends"

### ISSUE THREAD

**Issue by unfortunatelyalex** [Sovamorco/BHBot#7]
Since update 5.10 the bot repeatedly scrolls down in the main menu. 
It's not doing anything, just pressing "down" in a loop

https://user-images.githubusercontent.com/61123283/129423400-2d53ff09-57db-482a-b249-8496b3204968.mp4

**Comment by Sovamorco** [comment]
Most likely related to new menu. Thanks for the report, i'll try to fix it by the end of the day, hopefully.
