### ISSUE TITLE
Circulating at the interface

### ISSUE THREAD

**Issue by Real-king-Ph** [Sovamorco/BHBot#8]
https://user-images.githubusercontent.com/72426701/129470504-66f82f31-d48f-4fad-885c-e60c1ba9552f.mp4

Why did my program get stucked?

And,
Maybe we can add a new model.
In this game, if we exit and reenter and do not perform the operation, the game will have a robot to help us play the game.
And then Battle Pass is going to have some very time consuming activities, so let's turn that over to the robots, okay?

**Comment by Sovamorco** [comment]
In-game language has to be set to English for bot to work.

I'm not sure what you're talking about in the second part, but as far as I know Battle Pass missions can only be done in games versus real players. And using bots against players is very annoying and ruins game experience so if you're suggesting that, I'm not going to implement that at any point.

**Comment by Real-king-Ph** [comment]
I mean FFA.

I will complete it by myself.

Thanks for reply.
