### ISSUE TITLE
Bot is not choosing the character i want

### ISSUE THREAD

**Issue by shymeg** [Sovamorco/BHBot#9]
When i set the mode to: "Leveling up one character" and choosing Hattori, after creating custom game the bot chooses Queen Nai, seemingly still running in the "Leveling up characters closest to the next level". Thanks in advance

**Comment by unfortunatelyalex** [comment]
Did you set "Collapse crossovers" to "Yes"?

**Comment by Sovamorco** [comment]
Thanks for opening an issue. Please send a screenshot of the lobby (character selection screen) and logs, if possible.
Logs are located in %LOCALAPPDATA%\BHBot\logs. Just choose the log file with the date when that issue occured or the latest one.

**Comment by shymeg** [comment]
yeah, sure!
![image](https://user-images.githubusercontent.com/85294737/131364297-134c238f-9386-4500-aaf0-b02096cfc54a.png)
[20210830-150214.log](https://github.com/Sovamorco/BHBot/files/7077799/20210830-150214.log)

**Comment by shymeg** [comment]
> Did you set "Collapse crossovers" to "Yes"?

yes i did, i double checked it right now and it was set to yes the whole time

**Comment by Sovamorco** [comment]
Thanks a lot! I saw the problem and I'll fix it soon. It's related to server-sided program that parses characters currently in free rotation. I'll close the issue when I fix it.

**Comment by Sovamorco** [comment]
Try to run the bot again (make sure to restart the BHBot program itself so it can get rotation from the server). You're welcome to reopen this issue if anything goes wrong again.
